spring.application.name=furima
spring.datasource.url=jdbc:postgresql://localhost:5432/furima_development
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Thymeleaf設定
spring.thymeleaf.cache=false

# Flyway設定
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# キャメルケース設定
mybatis.configuration.map-underscore-to-camel-case=true

# 環境変数で設定している秘密鍵と公開鍵を参照させてる（pay.jpで使う）
payjp.secret-key=${PAYJP_SECRET_KEY}
payjp.public-key=${PAYJP_PUBLIC_KEY}