CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nickname VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255),
  last_name VARCHAR(255),
  first_name VARCHAR(255),
  last_name_kana VARCHAR(255),
  first_name_kana VARCHAR(255),
  birthday DATE
);